# drunner service configuration for minimalexample
#
---
configuration:

volumes:

containers:
   - drunner/minimalexample

commands:

help: |
   NAME
      ${SERVICENAME} - does nothing.

   SYNOPSIS
      ${SERVICENAME} help  - This help
      
